// tauri-tabs plugin 的命令清单。新增/删除 command 时同步这里，
// build 时会据此生成 autogenerated 权限与 ACL schema。
const COMMANDS: &[&str] = &[
    "navigate_webview",
    "emit_to_webview",
    "eval_webview",
    "open_devtools",
    "emit_to_host",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
