[package]
name = "tauri-tabs"
version = "0.1.0"
description = "Native Tauri tabbed webview demo"
authors = ["mozzie"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "tauri_tabs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.9.3", features = ["unstable"] }
tauri-plugin-tabs = { path = "../../tauri-plugin-tabs" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
